spring:
  application:
    name: demo
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_perfume
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org.springframework.security: DEBUG
jwt:
  secret: "1234567890123456789012345678901234567890123456789012345678901234"
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
Cloudinary:
  api-key: 617846343455642
  api-secret: d8Bymgntl4zcnn8QVRNVrZWGWQg
  cloud-name: drjj8x6wb

vnpay:
  tmn-code: 2I3WS0MP
  hash-secret: RH2901OGQEAAVO5WS1VUSZBBM45DVG3P
  pay-url:  https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/public/api/payment/vnpay-return
  ipn-url: http://localhost:8080/api/payments/vnpay-ipn
